spring.application.name=demo
server.port=8050

# MySQL 연결 정보
# spring.datasource.url=jdbc:mysql://192.168.100.221:30510/team5db
spring.datasource.url=jdbc:mysql://mysql-service:30511/team5db
spring.datasource.username=team5
spring.datasource.password=team5password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate 설정 (JPA 사용 시)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true